// Regenerates src/adapters.generated.ts from adapters/*/. Run after any
// change to an adapter.yaml or narrowed spec:
//
//   pnpm run generate:adapters
//
// The output is checked in so the Worker-safe root export needs no
// filesystem; tests/adapters-generated.test.ts fails when it goes stale.

import { readFileSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";
import { deriveAdapter, type DerivedAdapter } from "../adapter-derive";

const packageRoot = join(import.meta.dir, "..", "..");
const adaptersDir = join(packageRoot, "adapters");

const adapters: Record<string, DerivedAdapter> = {};
for (const provider of readdirSync(adaptersDir).sort()) {
  adapters[provider] = await deriveAdapter({
    provider,
    adapterYaml: readFileSync(join(adaptersDir, provider, "adapter.yaml"), "utf8"),
    specYaml: readFileSync(join(adaptersDir, provider, "openapi.angel.yaml"), "utf8"),
  });
}

const header = `// Generated by src/scripts/generate-adapters.ts — do not edit.
// Sources: adapters/<provider>/{adapter.yaml,openapi.angel.yaml}.

import type { DerivedAdapter } from "./adapter-derive";

export const GENERATED_ADAPTERS: Readonly<Record<string, DerivedAdapter>> = `;

writeFileSync(
  join(packageRoot, "src", "adapters.generated.ts"),
  `${header}${JSON.stringify(adapters, null, 2)};\n`,
);
console.log(`generated ${Object.keys(adapters).length} adapters: ${Object.keys(adapters).join(", ")}`);
