/* eslint-disable */
// Generated by Wrangler for the broker Worker.
interface __BaseEnv_BrokerEnv {
	CONTROL_BROKER_TOKEN: string;
	GATEWAY_BROKER_INVOKE_TOKEN: string;
	CREDENTIAL_KEK: string;
	GATES: DurableObjectNamespace<import("../src/workers/broker").GateRuntime>;
	CREDENTIAL_VAULTS: DurableObjectNamespace<import("../src/workers/broker").CredentialVault>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/workers/broker");
		durableNamespaces: "GateRuntime";
	}
	interface Env extends __BaseEnv_BrokerEnv {}
}
interface BrokerEnv extends __BaseEnv_BrokerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTROL_BROKER_TOKEN" | "GATEWAY_BROKER_INVOKE_TOKEN" | "CREDENTIAL_KEK">> {}
}
