/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.control.jsonc --include-runtime=false --env-interface=ControlEnv types/control.d.ts` (hash: d7ff2b04aa46264dc6046f4376f6f320)
interface __BaseEnv_ControlEnv {
	ASSETS: Fetcher;
	ACCOUNT_ID: "acct_m1";
	ACCESS_TEAM_DOMAIN: "https://angel-cloud.cloudflareaccess.com";
	ACCESS_AUDIENCE: "4848f84b13d92d4c9a219e35662c5ca84cd9b6188b5e556df801e34fb7bf1da7";
	CONTROL_BASE_URL: "https://dash.angelmcp.ai";
	AUTH_BASE_URL: "https://auth.angelmcp.ai";
	GATEWAY_BASE_URL: "https://mcp.angelmcp.ai";
	ACCOUNTS: DurableObjectNamespace<import("../src/workers/control").AccountRegistry>;
	GATEWAY: Fetcher /* angelmcp-gateway-demo */;
	BROKER: Fetcher /* angelmcp-broker-demo */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/workers/control");
		durableNamespaces: "AccountRegistry";
	}
	interface Env extends __BaseEnv_ControlEnv {}
}
interface ControlEnv extends __BaseEnv_ControlEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCOUNT_ID" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUDIENCE" | "CONTROL_BASE_URL" | "AUTH_BASE_URL" | "GATEWAY_BASE_URL">> {}
}
