/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.control.jsonc --include-runtime=false --env-interface=ControlEnv types/control.d.ts` (hash: 25d48dcc449c3ebdf4d3a1cad022d86d)
interface __BaseEnv_ControlEnv {
	ASSETS: Fetcher;
	CONTROL_BASE_URL: "https://dash.angelmcp.ai";
	GATEWAY_BASE_URL: "https://angelmcp-gateway-demo.sam-633.workers.dev";
	AUTH_BASE_URL: "https://auth.angelmcp.ai";
	ACCOUNTS: DurableObjectNamespace<import("../src/workers/control").AccountRegistry>;
	GATEWAY: Fetcher /* angelmcp-gateway-demo */;
	BROKER: Fetcher /* angelmcp-broker-demo */;
	AUTH: Fetcher /* angelmcp-auth */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/workers/control");
		durableNamespaces: "AccountRegistry";
	}
	interface Env extends __BaseEnv_ControlEnv {}
}
interface ControlEnv extends __BaseEnv_ControlEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTROL_BASE_URL" | "GATEWAY_BASE_URL" | "AUTH_BASE_URL">> {}
}
