/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=angel-cloud/wrangler.gateway.jsonc --env-file=/tmp/angelmcp-demo-vars-gateway --include-runtime=false --env-interface=GatewayEnv angel-cloud/types/gateway.d.ts` (hash: 8e3f08d890782b3a03f5e778c3423c6b)
interface __BaseEnv_GatewayEnv {
	CONTROL_GATEWAY_TOKEN: string;
	GATEWAY_BROKER_INVOKE_TOKEN: string;
	GATES: DurableObjectNamespace<import("../src/workers/gateway").GateRuntime>;
	BROKER: Fetcher /* angelmcp-broker-demo */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/workers/gateway");
		durableNamespaces: "GateRuntime";
	}
	interface Env extends __BaseEnv_GatewayEnv {}
}
interface GatewayEnv extends __BaseEnv_GatewayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTROL_GATEWAY_TOKEN" | "GATEWAY_BROKER_INVOKE_TOKEN">> {}
}
