/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=angel-cloud/wrangler.gateway.jsonc --env-file=/tmp/angelmcp-demo-vars-gateway --include-runtime=false --env-interface=GatewayEnv angel-cloud/types/gateway.d.ts` (hash: 15e061c4fe4de0a7518685bce358420a)
interface __BaseEnv_GatewayEnv {
	CONTROL_GATEWAY_TOKEN: string;
	GATEWAY_BROKER_INVOKE_TOKEN: string;
	GATES: DurableObjectNamespace<import("../src/workers/gateway").GateRuntime>;
	HANDLES: DurableObjectNamespace<import("../src/workers/gateway").HandleDirectory>;
	BROKER: Fetcher /* angelmcp-broker-demo */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/workers/gateway");
		durableNamespaces: "GateRuntime" | "HandleDirectory";
	}
	interface Env extends __BaseEnv_GatewayEnv {}
}
interface GatewayEnv extends __BaseEnv_GatewayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTROL_GATEWAY_TOKEN" | "GATEWAY_BROKER_INVOKE_TOKEN">> {}
}
