// Generated by src/scripts/generate-adapters.ts — do not edit.
// Sources: adapters/<provider>/{adapter.yaml,openapi.angel.yaml}.

import type { DerivedAdapter } from "./adapter-derive";

export const GENERATED_ADAPTERS: Readonly<Record<string, DerivedAdapter>> = {
  "docs": {
    "provider": "docs",
    "adapter": "google-discovery@1",
    "credential": "google_oauth",
    "origin": "https://docs.googleapis.com",
    "source": "https://docs.googleapis.com/$discovery/rest?version=v1",
    "sourceDigest": "sha256:a2264026a07286c5555ca9f42c16fc2581b558a11ab6c95085cd0af3355c530e",
    "scopeRanking": [
      "https://www.googleapis.com/auth/documents.readonly",
      "https://www.googleapis.com/auth/documents"
    ],
    "operations": {
      "docs.documents.get": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/v1/documents/{documentId}",
          "pathParams": [
            "documentId"
          ],
          "pathDefaults": {},
          "queryParams": [
            "includeTabsContent",
            "suggestionsViewMode"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://www.googleapis.com/auth/documents",
          "https://www.googleapis.com/auth/documents.readonly",
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/drive.file",
          "https://www.googleapis.com/auth/drive.readonly"
        ]
      }
    }
  },
  "gmail": {
    "provider": "gmail",
    "adapter": "google-discovery@1",
    "credential": "google_oauth",
    "origin": "https://gmail.googleapis.com",
    "source": "https://gmail.googleapis.com/$discovery/rest?version=v1",
    "sourceDigest": "sha256:20c855852c32eea2488376e1e1a555665cd4ab5feca4d7a78b26ee1ff0cddf22",
    "scopeRanking": [
      "https://www.googleapis.com/auth/gmail.readonly",
      "https://www.googleapis.com/auth/gmail.labels",
      "https://www.googleapis.com/auth/gmail.compose",
      "https://www.googleapis.com/auth/gmail.settings.basic",
      "https://www.googleapis.com/auth/gmail.modify"
    ],
    "operations": {
      "gmail.users.drafts.create": {
        "request": {
          "kind": "http",
          "method": "POST",
          "pathTemplate": "/gmail/v1/users/{userId}/drafts",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": true
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
          "https://www.googleapis.com/auth/gmail.compose",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      },
      "gmail.users.drafts.list": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/drafts",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [
            "includeSpamTrash",
            "maxResults",
            "pageToken",
            "q"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.compose",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.drafts.get": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/drafts/{id}",
          "pathParams": [
            "userId",
            "id"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [
            "format"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.compose",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.drafts.update": {
        "request": {
          "kind": "http",
          "method": "PUT",
          "pathTemplate": "/gmail/v1/users/{userId}/drafts/{id}",
          "pathParams": [
            "userId",
            "id"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": true
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
          "https://www.googleapis.com/auth/gmail.compose",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      },
      "gmail.users.history.list": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/history",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [
            "historyTypes",
            "labelId",
            "maxResults",
            "pageToken",
            "startHistoryId"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.labels.list": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/labels",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.labels",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.labels.create": {
        "request": {
          "kind": "http",
          "method": "POST",
          "pathTemplate": "/gmail/v1/users/{userId}/labels",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": true
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.labels",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      },
      "gmail.users.labels.delete": {
        "request": {
          "kind": "http",
          "method": "DELETE",
          "pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
          "pathParams": [
            "userId",
            "id"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.labels",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      },
      "gmail.users.labels.update": {
        "request": {
          "kind": "http",
          "method": "PUT",
          "pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
          "pathParams": [
            "id",
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": true
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.labels",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      },
      "gmail.users.labels.get": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
          "pathParams": [
            "userId",
            "id"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.labels",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.labels.patch": {
        "request": {
          "kind": "http",
          "method": "PATCH",
          "pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
          "pathParams": [
            "id",
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": true
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.labels",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      },
      "gmail.users.messages.list": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/messages",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [
            "includeSpamTrash",
            "labelIds",
            "maxResults",
            "pageToken",
            "q"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.messages.get": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/messages/{id}",
          "pathParams": [
            "id",
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [
            "format",
            "metadataHeaders"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.addons.current.message.action",
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.messages.modify": {
        "request": {
          "kind": "http",
          "method": "POST",
          "pathTemplate": "/gmail/v1/users/{userId}/messages/{id}/modify",
          "pathParams": [
            "userId",
            "id"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": true
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      },
      "gmail.users.messages.attachments.get": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
          "pathParams": [
            "messageId",
            "id",
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.addons.current.message.action",
          "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.getProfile": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/profile",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.compose",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.settings.getAutoForwarding": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/settings/autoForwarding",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
        ]
      },
      "gmail.users.settings.getVacation": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/settings/vacation",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
        ]
      },
      "gmail.users.threads.list": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/threads",
          "pathParams": [
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [
            "includeSpamTrash",
            "labelIds",
            "maxResults",
            "pageToken",
            "q"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.threads.get": {
        "request": {
          "kind": "http",
          "method": "GET",
          "pathTemplate": "/gmail/v1/users/{userId}/threads/{id}",
          "pathParams": [
            "id",
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [
            "format",
            "metadataHeaders"
          ],
          "hasBody": false
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.addons.current.message.action",
          "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
          "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
          "https://www.googleapis.com/auth/gmail.metadata",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
        ]
      },
      "gmail.users.threads.modify": {
        "request": {
          "kind": "http",
          "method": "POST",
          "pathTemplate": "/gmail/v1/users/{userId}/threads/{id}/modify",
          "pathParams": [
            "id",
            "userId"
          ],
          "pathDefaults": {
            "userId": "me"
          },
          "queryParams": [],
          "hasBody": true
        },
        "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify"
        ]
      }
    }
  }
};
