#!/usr/bin/env bun
// Record what ledger-render inlined into docs/product-ledger.html.
//
//   bun scripts/ledger-fingerprint.ts            # check (exit 1 on drift)
//   bun scripts/ledger-fingerprint.ts --write    # re-record after a toolkit upgrade
//
// The Product Ledger is generated by an external toolkit that has no remote
// (an open owner decision), so a machine without it cannot re-render to compare.
// This pins the three parts the generator inlines — the Card stylesheet, the
// renderer, and the page shell around them — so a hand edit to the generated
// page fails the suite anywhere, toolkit or not. The dataroom itself is checked
// separately, by comparing the inlined JSON to datarooms/angel-cloud.json.

import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const PAGE = join(ROOT, "docs/product-ledger.html");
const FINGERPRINT = join(ROOT, "datarooms/ledger-render.fingerprint.json");

const sha = (s: string) => new Bun.CryptoHasher("sha256").update(s).digest("hex");

export function parts(html: string) {
  const css = html.match(/<style>\n([\s\S]*?)\n<\/style>/)?.[1];
  const renderer = html.match(/<script>\n([\s\S]*?)\n<\/script>\n<\/body>/)?.[1];
  if (css == null || renderer == null) {
    throw new Error("docs/product-ledger.html is not a ledger-render page: no inlined style or renderer");
  }
  const shell = html
    .replace(/<script id="ledger" type="application\/json">[\s\S]*?<\/script>/, "<!--DATAROOM-->")
    .replace(/<style>\n[\s\S]*?\n<\/style>/, "<!--CSS-->")
    .replace(/<script>\n[\s\S]*?\n<\/script>\n<\/body>/, "<!--JS-->\n</body>");
  return { css: sha(css), renderer: sha(renderer), shell: sha(shell) };
}

if (import.meta.main) {
  const html = await Bun.file(PAGE).text();
  const actual = parts(html);
  const recorded = JSON.parse(await Bun.file(FINGERPRINT).text());

  if (Bun.argv.includes("--write")) {
    await Bun.write(FINGERPRINT, JSON.stringify({ ...recorded, ...actual }, null, 2) + "\n");
    console.log("recorded", actual);
    process.exit(0);
  }

  const drift = (["css", "renderer", "shell"] as const).filter((k) => recorded[k] !== actual[k]);
  if (!drift.length) {
    console.log("✓ docs/product-ledger.html matches the recorded render fingerprint");
    process.exit(0);
  }
  console.error(`✗ ${drift.join(", ")} changed without a recorded toolkit upgrade.`);
  console.error("  Re-render from the dataroom, or run --write if the toolkit legitimately moved.");
  process.exit(1);
}
